project:
  type: website
  output-dir: docs
website:
  title: "Stubler Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: outreach.qmd
        text: Teaching and Outreach
      - href: publications.qmd
        text: Publications
        
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

